name: ":: build Pact FFI"

on:
  workflow_call:
    inputs:
      commit-sha:
        required: false
        type: string
      repo-owner:
        required: true
        type: string
      repo-name:
        required: true
        type: string

jobs:
  build-ffi:
    name: "ğŸš§  Build libpact_ffi.a"
    runs-on: macos-14
    timeout-minutes: 60
    strategy:
      fail-fast: true

    steps:
      - name: "â™»ï¸ Checkout"
        uses: actions/checkout@v4

      - name: "â™¼ Cache rust binaries"
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}
          key: build-ffi-${{ runner.os }}-${{ hashFiles('**/Package.swift') }}
          restore-keys: |
            build-ffi-${{ runner.os }}

      - name: "ğŸ”  Check for cached files"
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: "PactSwiftMockServer/**/libpact_ffi.version"

      - name: "ğŸ§‘â€ğŸ¤â€ğŸ§‘ Clone ${{ inputs.repo-owner }}/${{ inputs.repo-name }}"
        uses: GuillaumeFalourd/clone-github-repo-action@v2.1
        if: steps.check_files.outputs.files_exists == 'false'
        with:
          owner: ${{ inputs.repo-owner }}
          repository: ${{ inputs.repo-name }}

      - name: "ğŸ§°  Install required tools"
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          sh Scripts/install_required_tools

      - name: "ğŸ› ï¸  Build FFI"
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          cd ${{ inputs.repo-name }}
          sh ../Scripts/build_ffi_libs ${{ inputs.commit-sha }}

      - name: "ğŸ›«  Upload artifacts"
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: "Resources"
          path: ${{ inputs.repo-name }}/Resources
